basics.model.complexity: code/basics.model.complexity.py
	python $<
basics.model.selection: code/basics.model.selection.py
	python $<
applications.peptide.binding: code/applications.peptide.binding.py
	python $<
bootstrap.tutorial:
	pip install virtualenv
	virtualenv env
	source ./env/bin/activate
	pip install numpy --upgrade
	pip install scipy --upgrade
	pip install matplotlib --upgrade
	pip install scikit-learn --upgrade
	pip install seaborn --upgrade
